// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('postdata', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('postdata', async function() {
    await driver.get("https://social-mern.netlify.app/")
    await driver.manage().window().setRect({ width: 1050, height: 964 })
    await driver.findElement(By.css(".text-area-in-feed")).click()
    await driver.findElement(By.css(".text-area-in-feed")).sendKeys("afgdfg")
    await driver.findElement(By.id("photo")).click()
    await driver.findElement(By.id("photo")).sendKeys("C:\\fakepath\\th.jpg")
    await driver.findElement(By.css(".create-post-btn")).click()
    await driver.close()
  })
})
