// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ssdd', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ssdd', async function() {
    
  })
})
const fs = require('fs');
const csv = require('csv-parser');
const { Builder, By, until } = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');

const chromeDriverPath = 'H:\\BSSE606\\webdriver\\chromedriver\\chromedriver.exe'; // Ensure .exe extension for Windows

fs.createReadStream('phone.csv')
  .pipe(csv())
  .on('data', async (data) => {
    // Initialize WebDriver for each data entry
    let driver = await new Builder()
      .forBrowser('chrome')
      .setChromeOptions(new chrome.Options())
      .setChromeService(new chrome.ServiceBuilder(chromeDriverPath))
      .build();

    try {await driver.get("https://social-mern.netlify.app/")
    await driver.manage().window().setRect({ width: 1050, height: 964 })
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.css(".sign-in-form")).click()
    await driver.findElement(By.css(".cursor-pointer")).click()
    await driver.close()
    await driver.findElement(By.css(".sign-in-form")).click()
    await driver.findElement(By.css(".sign-in-form")).click()
    await driver.findElement(By.css(".signin-btn")).click()
    await driver.findElement(By.css(".signin-btn")).click()
    {
      const element = await driver.findElement(By.css(".app-btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".toggle > path")).click()
    await driver.findElement(By.css(".nav-link:nth-child(5) .text")).click()
    await driver.findElement(By.id("firstname")).click()
    await driver.findElement(By.id("firstname")).sendKeys(data.fname)
    await driver.findElement(By.id("lastname")).click()
    await driver.findElement(By.id("lastname")).sendKeys(data.lname)
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys(data.d)
    await driver.findElement(By.id("city")).click()
    await driver.findElement(By.id("city")).sendKeys(data.city)
    await driver.findElement(By.css(".input-radio--btns > label:nth-child(2)")).click()
    await driver.findElement(By.name("dob")).click()
    await driver.findElement(By.name("dob")).click()
    await driver.findElement(By.name("dob")).sendKeys("2023-12-13")
    await driver.findElement(By.id("marital-status")).click()
    await driver.findElement(By.id("age")).click()
    {
      const dropdown = await driver.findElement(By.id("age"))
      await dropdown.findElement(By.xpath("//option[. = '42']")).click()
    }
    await driver.findElement(By.id("address")).click()
    await driver.findElement(By.id("address")).sendKeys("dfsdfsfdsdfsf")
    await driver.findElement(By.css(".edit-form--btns:nth-child(10) > .primary-btn:nth-child(1)")).click()
    await driver.findElement(By.css(".Toastify__close-button > svg")).click()
    await driver.findElement(By.css(".cursor-pointer")).click()
    await driver.close()
      

      // Check if sign-in was successful based on URL
      const currentUrl = await driver.getCurrentUrl();
      if (currentUrl === 'https://social-mern.netlify.app/profile') {
        console.log("Test passed for:", data.fname);
      } else {
        console.log("Test failed for:", data.fname);
      }
    } catch (error) {
      console.error('Error occurred:', error);
      console.log("Test failed for:", data.fname);
    } finally {
      await driver.quit();
    }
  })
  .on('end', () => {
    console.log('Test data iteration complete');
  });
